"""``opencoat demo`` — one-line guided tour of the OpenCOAT pickup loop.

This is the "zero Python paste" path the ``opencoat-skill`` quickstart
points users at: instead of asking them to write a ~40-line
``demo_host.py``, the CLI wires a tiny in-script ``FakeHost``,
subscribes :func:`install_hooks`, fires three demo events, and prints
**BEFORE / AFTER** for each scene so concerns visibly change the
host's mutable state on first read.

Two modes:

* **default** (daemon-backed) — connects to the running daemon (the
  one ``opencoat runtime up`` exposes). Concerns are expected to be
  seeded via ``opencoat concern import --demo``; the daemon owns
  them and the DCN. Activations show up in
  ``opencoat dcn activation-log`` afterwards.
* **``--in-proc``** — no daemon required. Builds an in-process
  :class:`OpenCOATRuntime`, seeds :func:`demo_concerns` directly,
  runs the same three scenes against it. Useful for a cold tour
  where the user hasn't run ``runtime up`` yet.

``--script-out PATH`` writes the equivalent ``demo_host.py`` to disk
and exits without running anything — handy for users who want a
runnable template to adapt for their own host.

The CLI lives in ``opencoat-runtime`` but the demo logic relies on
``opencoat-runtime-host`` for :class:`OpenClawAdapter` /
:func:`install_hooks` (the pickup API). We **lazy import** that
package and fail with a friendly hint if it's missing, so
``pipx install opencoat-runtime`` users get a clear "install the host
SDK too" message rather than an opaque ``ModuleNotFoundError``.
"""

from __future__ import annotations

import argparse
import sys
from collections.abc import Callable
from dataclasses import dataclass, field
from pathlib import Path
from typing import TYPE_CHECKING, Any

from .._http import add_endpoint_args, resolve_endpoint

if TYPE_CHECKING:
    from opencoat_runtime_protocol import ConcernInjection, JoinpointEvent


# ---------------------------------------------------------------------------
# Hints — kept module-level so tests can pin the strings users see
# ---------------------------------------------------------------------------

DAEMON_UNREACHABLE_HINT = (
    "opencoat demo: could not reach the daemon.\n"
    "  Start it with:\n"
    "    opencoat runtime up\n"
    "    opencoat concern import --demo\n"
    "  ...or run a daemon-less tour:\n"
    "    opencoat demo --in-proc"
)

HOST_SDK_MISSING_HINT = (
    "opencoat demo: needs the opencoat-runtime-host package (OpenClaw "
    "adapter + host SDK).\n"
    "  Install it alongside opencoat-runtime:\n"
    "    pipx inject opencoat-runtime opencoat-runtime-host\n"
    "  Or from source:\n"
    "    pip install 'git+https://github.com/HyperdustLabs/OpenCOAT.git"
    "#subdirectory=packages/opencoat-runtime-host'"
)

NO_CONCERNS_SEEDED_HINT = (
    "opencoat demo: the daemon has no demo concerns seeded (every scene "
    "would no-op).\n"
    "  Seed them with:\n"
    "    opencoat concern import --demo"
)


# ---------------------------------------------------------------------------
# The Python script we dump for ``--script-out`` — kept in sync with
# the live scene runner below so users get a faithful "learn the
# pattern" template. Pinned by ``test_script_out_writes_runnable_demo``.
# ---------------------------------------------------------------------------

_DEMO_SCRIPT_TEMPLATE = '''"""Equivalent to ``opencoat demo`` — kept verbatim for learning purposes.

Generated by ``opencoat demo --script-out``. Run with the venv that
has ``opencoat-runtime`` + ``opencoat-runtime-host`` installed:

    python demo_host.py

Assumes a daemon is up on the URL below and that
``opencoat concern import --demo`` has been run.
"""

from __future__ import annotations

from collections.abc import Callable
from dataclasses import dataclass, field
from typing import Any

from opencoat_runtime_host_openclaw import (
    OpenClawAdapter,
    OpenClawMemoryBridge,
    install_hooks,
)
from opencoat_runtime_host_sdk import Client
from opencoat_runtime_protocol import ConcernInjection, JoinpointEvent

DAEMON_URL = {daemon_url!r}


@dataclass
class FakeHost:
    """Tiny in-script stand-in for an OpenClaw-shaped host."""

    subscriptions: dict[str, list[Callable[[dict[str, Any]], None]]] = field(default_factory=dict)

    def subscribe(self, event_name, callback):
        self.subscriptions.setdefault(event_name, []).append(callback)
        return lambda: self.subscriptions[event_name].remove(callback)

    def fire(self, event_name, payload):
        for cb in list(self.subscriptions.get(event_name, [])):
            cb(payload)


class DaemonRuntime:
    """RuntimeLike proxy: forwards every event to the daemon over HTTP."""

    def __init__(self, client: Client) -> None:
        self._client = client

    def on_joinpoint(
        self,
        jp: JoinpointEvent,
        *,
        context: dict[str, Any] | None = None,
        return_none_when_empty: bool = False,
    ) -> ConcernInjection | None:
        return self._client.emit(jp, context=context, return_none_when_empty=return_none_when_empty)


def main() -> None:
    client = Client.connect(DAEMON_URL)
    host = FakeHost()
    installed = install_hooks(
        host,
        runtime=DaemonRuntime(client),
        adapter=OpenClawAdapter(),
        bridge=OpenClawMemoryBridge(dcn_store=None),
        event_names=("agent.started", "agent.before_tool", "agent.memory_write"),
    )
    try:
        # Scene 1 — prompt folding
        prompt_before = {{"runtime_prompt": {{"active_concerns": ""}}}}
        host.fire("agent.started", {{"host_round_id": "t-1", "payload": {{}}}})
        prompt_after = installed.apply_to(prompt_before)
        print("PROMPT before:", prompt_before["runtime_prompt"]["active_concerns"] or "<empty>")
        print("PROMPT after :", prompt_after["runtime_prompt"]["active_concerns"])

        # Scene 2 — tool guard
        tool_call = {{"name": "shell.exec", "arguments": {{"command": "rm -rf /tmp/scratch"}}}}
        host.fire(
            "agent.before_tool",
            {{"host_round_id": "t-1", "payload": {{"content": "shell.exec rm -rf /tmp/scratch"}}}},
        )
        outcome = installed.guard_tool_call(tool_call)
        verdict = "BLOCKED" if outcome and outcome.blocked else "allowed"
        reason = outcome.block_reason if outcome else ""
        print(f"TOOL    : {{verdict}} {{reason}}")

        # Scene 3 — memory write
        host.fire("agent.memory_write", {{"host_round_id": "t-1", "payload": {{"key": "k", "value": "v"}}}})
        memory_after = installed.apply_to({{"memory_write": {{"policy_note": ""}}}})
        print("MEMORY  :", memory_after["memory_write"]["policy_note"])
    finally:
        installed.uninstall()


if __name__ == "__main__":
    main()
'''


# ---------------------------------------------------------------------------
# Subscribe-shaped fake host — the smallest thing install_hooks can drive.
# ---------------------------------------------------------------------------


@dataclass
class _FakeHost:
    subscriptions: dict[str, list[Callable[[dict[str, Any]], None]]] = field(default_factory=dict)

    def subscribe(
        self,
        event_name: str,
        callback: Callable[[dict[str, Any]], None],
    ) -> Callable[[], None]:
        self.subscriptions.setdefault(event_name, []).append(callback)

        def _unsubscribe() -> None:
            self.subscriptions[event_name].remove(callback)

        return _unsubscribe

    def fire(self, event_name: str, payload: dict[str, Any]) -> None:
        for cb in list(self.subscriptions.get(event_name, [])):
            cb(payload)


# ---------------------------------------------------------------------------
# RuntimeLike proxy for the daemon path. Keep tiny so the seam shows in
# code review — ``install_hooks`` only ever calls ``.on_joinpoint``.
# ---------------------------------------------------------------------------


class _DaemonRuntime:
    def __init__(self, client: Any) -> None:
        self._client = client

    def on_joinpoint(
        self,
        jp: JoinpointEvent,
        *,
        context: dict[str, Any] | None = None,
        return_none_when_empty: bool = False,
    ) -> ConcernInjection | None:
        return self._client.emit(
            jp,
            context=context,
            return_none_when_empty=return_none_when_empty,
        )


# ---------------------------------------------------------------------------
# Scene runner — same shape for both daemon and in-proc paths.
# ---------------------------------------------------------------------------


def _print_scene_header(idx: int, title: str, concern_id: str) -> None:
    print(f"[{idx}/3] {title} — concern: {concern_id}")


def _run_scenes(host: _FakeHost, installed: Any, *, stream: Any = None) -> int:
    """Walk the three pickup-API scenes against ``host`` + ``installed``.

    Returns 0 when every scene produced the expected visible change,
    1 when at least one scene was a no-op (concern not active, payload
    didn't match, etc.). Callers print a follow-up hint based on the
    return code.
    """
    out = stream or sys.stdout
    failed: list[str] = []

    # ------------------------------------------------------------------
    # Scene 1 — prompt folding
    # ------------------------------------------------------------------
    _print_scene_header(1, "PROMPT FOLDING", "demo-prompt-prefix")
    prompt_before: dict[str, Any] = {"runtime_prompt": {"active_concerns": ""}}
    host.fire("agent.started", {"host_round_id": "demo-t1", "payload": {}})
    prompt_after = installed.apply_to(prompt_before)
    before_val = prompt_before["runtime_prompt"]["active_concerns"] or '""'
    after_val = prompt_after["runtime_prompt"].get("active_concerns", "")
    print("  fire event : agent.started", file=out)
    print("  prompt slot: runtime_prompt.active_concerns", file=out)
    print(f"  BEFORE     : {before_val}", file=out)
    print(f"  AFTER      : {after_val or '<no change — concern inactive?>'}", file=out)
    if not after_val:
        failed.append("demo-prompt-prefix")
        print("  ⚠ no advice folded — is demo-prompt-prefix active?", file=out)
    else:
        print("  → apply_to() folded demo-prompt-prefix into the prompt slot.", file=out)
    print(file=out)

    # ------------------------------------------------------------------
    # Scene 2 — tool guard
    # ------------------------------------------------------------------
    _print_scene_header(2, "TOOL GUARD", "demo-tool-block")
    tool_call: dict[str, Any] = {
        "name": "shell.exec",
        "arguments": {"command": "rm -rf /tmp/scratch"},
    }
    host.fire(
        "agent.before_tool",
        # ``demo-tool-block`` matches keywords against payload
        # text/content/raw_text/token, so we mirror the command line
        # into ``content`` so the matcher sees it.
        {"host_round_id": "demo-t1", "payload": {"content": "shell.exec rm -rf /tmp/scratch"}},
    )
    outcome = installed.guard_tool_call(tool_call)
    print("  fire event : agent.before_tool (payload includes 'rm -rf')", file=out)
    print(f"  tool call  : {tool_call['name']} {tool_call['arguments']['command']}", file=out)
    if outcome is not None and outcome.blocked:
        print("  outcome    : BLOCKED", file=out)
        print(f"  reason     : {outcome.block_reason}", file=out)
        print("  → guard_tool_call() returned blocked=True. Host should refuse.", file=out)
    else:
        failed.append("demo-tool-block")
        print("  outcome    : allowed (no TOOL_GUARD advice fired)", file=out)
        print(
            "  ⚠ is demo-tool-block active? keyword matcher needs 'rm -rf' in payload text.",
            file=out,
        )
    print(file=out)

    # ------------------------------------------------------------------
    # Scene 3 — memory write annotation
    # ------------------------------------------------------------------
    _print_scene_header(3, "MEMORY NOTE", "demo-memory-tag")
    memory_before: dict[str, Any] = {"memory_write": {"policy_note": ""}}
    host.fire(
        "agent.memory_write",
        {"host_round_id": "demo-t1", "payload": {"key": "preferences.tone", "value": "concise"}},
    )
    memory_after = installed.apply_to(memory_before)
    before_note = memory_before["memory_write"]["policy_note"] or '""'
    after_note = memory_after["memory_write"].get("policy_note", "")
    print("  fire event : agent.memory_write", file=out)
    print("  memory slot: memory_write.policy_note", file=out)
    print(f"  BEFORE     : {before_note}", file=out)
    print(f"  AFTER      : {after_note or '<no change>'}", file=out)
    if not after_note:
        failed.append("demo-memory-tag")
        print("  ⚠ no advice folded — is demo-memory-tag active?", file=out)
    else:
        print("  → apply_to() annotated memory_write.policy_note.", file=out)
    print(file=out)

    if failed:
        print(f"✗ {len(failed)} scene(s) produced no visible change: {', '.join(failed)}", file=out)
        print(NO_CONCERNS_SEEDED_HINT, file=out)
        return 1

    print("✓ All three scenes produced visible host-context changes.", file=out)
    print(file=out)
    print("Next:", file=out)
    print("  • opencoat dcn activation-log --limit 10        # which concerns fired", file=out)
    print("  • opencoat concern list                          # what's seeded", file=out)
    print(
        "  • opencoat plugin install openclaw               # scaffold a real host plugin", file=out
    )
    print(
        "  • opencoat demo --script-out demo_host.py        # dump the equivalent Python", file=out
    )
    return 0


# ---------------------------------------------------------------------------
# Daemon-backed mode
# ---------------------------------------------------------------------------


def _build_daemon_url(args: argparse.Namespace) -> str:
    host, port, path = resolve_endpoint(args)
    path = path if path.startswith("/") else f"/{path}"
    return f"http://{host}:{port}{path}"


def _run_against_daemon(args: argparse.Namespace) -> int:
    # Lazy host-SDK imports so ``opencoat demo --in-proc`` users with
    # only ``opencoat-runtime`` installed get the friendly hint below
    # rather than a hard import failure here.
    try:
        from opencoat_runtime_host_openclaw import (
            OpenClawAdapter,
            OpenClawMemoryBridge,
            install_hooks,
        )
        from opencoat_runtime_host_sdk import Client
    except ImportError:
        print(HOST_SDK_MISSING_HINT, file=sys.stderr)
        return 2

    from opencoat_runtime_host_sdk.transport.http import (
        HostTransportConnectionError,
    )

    url = _build_daemon_url(args)
    try:
        client = Client.connect(url)
        # Cheap health probe so we fail with a single helpful message
        # rather than three separate ``HostTransportConnectionError``
        # mid-demo. ``Client.emit`` would raise on first event anyway,
        # but mid-scene errors look like a bug in the demo, not config.
        client.transport._call("health.ping", {})
    except HostTransportConnectionError:
        print(DAEMON_UNREACHABLE_HINT, file=sys.stderr)
        return 2

    print(f"== OpenCOAT demo — daemon @ {url} ==")
    print()
    print("Firing 3 events through install_hooks; folding the returned advice")
    print("back into a tiny in-script FakeHost via apply_to / guard_tool_call.")
    print()

    host = _FakeHost()
    installed = install_hooks(
        host,
        runtime=_DaemonRuntime(client),
        adapter=OpenClawAdapter(),
        bridge=OpenClawMemoryBridge(dcn_store=None),
        event_names=("agent.started", "agent.before_tool", "agent.memory_write"),
    )
    try:
        return _run_scenes(host, installed)
    finally:
        installed.uninstall()


# ---------------------------------------------------------------------------
# In-process mode — no daemon, no concern import. One shot.
# ---------------------------------------------------------------------------


def _run_in_proc(_args: argparse.Namespace) -> int:
    try:
        from opencoat_runtime_host_openclaw import (
            OpenClawAdapter,
            OpenClawMemoryBridge,
            install_hooks,
        )
    except ImportError:
        print(HOST_SDK_MISSING_HINT, file=sys.stderr)
        return 2

    from opencoat_runtime_core import OpenCOATRuntime, RuntimeConfig
    from opencoat_runtime_core.llm import StubLLMClient
    from opencoat_runtime_storage.memory import MemoryConcernStore, MemoryDCNStore

    from ..demo_concerns import demo_concerns

    runtime = OpenCOATRuntime(
        RuntimeConfig(),
        concern_store=MemoryConcernStore(),
        dcn_store=MemoryDCNStore(),
        llm=StubLLMClient(),
    )
    for concern in demo_concerns():
        runtime.concern_store.upsert(concern)
        runtime.dcn_store.add_node(concern)

    print("== OpenCOAT demo — in-proc (no daemon) ==")
    print()
    print("Built an in-process OpenCOATRuntime, seeded 3 demo concerns,")
    print("and wired install_hooks against a tiny in-script FakeHost.")
    print()

    host = _FakeHost()
    installed = install_hooks(
        host,
        runtime=runtime,
        adapter=OpenClawAdapter(),
        bridge=OpenClawMemoryBridge(dcn_store=runtime.dcn_store),
        event_names=("agent.started", "agent.before_tool", "agent.memory_write"),
    )
    try:
        return _run_scenes(host, installed)
    finally:
        installed.uninstall()


# ---------------------------------------------------------------------------
# Entry point + argparse wiring
# ---------------------------------------------------------------------------


def _handle(args: argparse.Namespace) -> int:
    if args.script_out is not None:
        # ``--script-out`` is write-and-exit so users can read the
        # script offline before running it. Running the demo itself
        # is opt-in via a separate invocation (``opencoat demo``).
        url = _build_daemon_url(args) if not args.in_proc else "http://127.0.0.1:7878/rpc"
        path = Path(args.script_out)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(_DEMO_SCRIPT_TEMPLATE.format(daemon_url=url))
        print(f"opencoat demo: wrote {path}")
        print("  Run it with:  python", path)
        return 0

    if args.in_proc:
        return _run_in_proc(args)
    return _run_against_daemon(args)


def register(sub: argparse._SubParsersAction) -> None:
    p = sub.add_parser(
        "demo",
        help="run a 3-scene tour of the OpenCOAT pickup loop (prompt fold, tool guard, memory note)",
    )
    p.add_argument(
        "--in-proc",
        action="store_true",
        help="don't connect to a daemon; build an in-process runtime and seed demo concerns",
    )
    p.add_argument(
        "--script-out",
        type=Path,
        default=None,
        help="write the equivalent demo_host.py to PATH and exit (no demo run)",
    )
    add_endpoint_args(p)
    p.set_defaults(func=_handle)


__all__ = [
    "DAEMON_UNREACHABLE_HINT",
    "HOST_SDK_MISSING_HINT",
    "NO_CONCERNS_SEEDED_HINT",
    "register",
]
