"""Working :class:`CustomHostAdapter` for a bespoke agent framework.

Generated by ``opencoat plugin install custom``.

Both halves of the :class:`HostAdapter` contract are implemented here
end-to-end so the scaffold is "import + run" out of the box:

* :meth:`map_host_event` walks :data:`_EVENT_NAME_KEYS` in order and
  uses the first non-empty string value that appears as a key in the
  active event map (so a mixed envelope like ``type: "audit"`` plus
  ``event_name: "agent.user_message"`` still resolves). It then
  returns a fully-formed
  :class:`JoinpointEvent` (with ``id`` / ``ts`` / ``level`` filled in
  against :data:`JOINPOINT_CATALOG`).
* :meth:`apply_injection` deep-copies ``host_context``, walks every
  :class:`Injection`'s dotted ``target`` to a leaf, and applies the
  weaving operation (append for ``INSERT`` / ``ANNOTATE`` / ``WARN`` /
  ``VERIFY`` / ``DEFER``; overwrite for ``REPLACE`` / ``REWRITE`` /
  ``COMPRESS`` / ``SUPPRESS`` / ``BLOCK`` / ``ESCALATE``).

Both surfaces are deliberately self-contained — no
``opencoat-runtime-host`` import — so a runtime-only install
(``pipx install opencoat-runtime``) can still wire the adapter
directly to an in-process :class:`OpenCOATRuntime`.

To adapt this to your framework, the two extension points are:

* :data:`EVENT_TO_JOINPOINT` — host event name → OpenCOAT joinpoint
  name. Everything in the table must be a key in
  :data:`opencoat_runtime_core.joinpoint.JOINPOINT_CATALOG` (see
  ``opencoat inspect joinpoints``).
* :data:`_EVENT_NAME_KEYS` — ordered keys to probe for the host event
  name string. The first value that appears in the active event map wins.

For OpenClaw-shaped hosts, the much richer
:class:`opencoat_runtime_host_openclaw.OpenClawAdapter` is a better
starting point — it already speaks the OpenClaw event vocabulary and
adds the ``tool_guard`` decision surface this scaffold deliberately
leaves out.
"""

from __future__ import annotations

import copy
import uuid
from collections.abc import Iterable
from datetime import UTC, datetime
from typing import Any

from opencoat_runtime_core.joinpoint import JOINPOINT_CATALOG, JoinpointLevel
from opencoat_runtime_core.ports import HostAdapter
from opencoat_runtime_protocol import (
    ConcernInjection,
    Injection,
    JoinpointEvent,
    WeavingOperation,
)

# ---------------------------------------------------------------------------
# Knobs you'll edit when adapting this to your framework
# ---------------------------------------------------------------------------

#: Host event name → OpenCOAT joinpoint name.
#:
#: Each value MUST be a key in
#: :data:`opencoat_runtime_core.joinpoint.JOINPOINT_CATALOG` (run
#: ``opencoat inspect joinpoints`` for the full list). Unknown event
#: names return ``None`` from :meth:`CustomHostAdapter.map_host_event`,
#: which the runtime ignores rather than crashing on.
EVENT_TO_JOINPOINT: dict[str, str] = {
    # Lifecycle / runtime
    "agent.started": "runtime_start",
    "runtime.start": "runtime_start",
    # Conversation
    "agent.user_message": "on_user_input",
    "user.message": "on_user_input",
    "before_response": "before_response",
    "agent.before_response": "before_response",
    # Tools
    "agent.before_tool_call": "before_tool_call",
    "tool.before_call": "before_tool_call",
    "before_tool_call": "before_tool_call",
    # Memory
    "agent.memory_write": "before_memory_write",
    "memory.before_write": "before_memory_write",
    "before_memory_write": "before_memory_write",
}

# Where in the inbound event dict to look for the event name, in priority order.
# Each candidate string is accepted only if it exists in the active event map;
# otherwise the next key is tried (avoids losing real joinpoints when hosts
# carry both a coarse ``type`` and a fine-grained ``event_name``).
_EVENT_NAME_KEYS: tuple[str, ...] = ("type", "name", "event", "event_name")

# Fields lifted from the inbound event into the JoinpointEvent envelope
# (rather than being mirrored verbatim into ``payload``).
_ENVELOPE_KEYS: frozenset[str] = frozenset(
    {
        "id",
        "ts",
        "agent_session_id",
        "host_round_id",
        "turn_id",
        "weave_id",
        "host",
        "level",
        "payload",
        *_EVENT_NAME_KEYS,
    }
)

# Default joinpoint level for events whose mapped name isn't in
# :data:`JOINPOINT_CATALOG`. Should almost never fire — every entry in
# :data:`EVENT_TO_JOINPOINT` ships pre-validated against the catalog.
_FALLBACK_LEVEL = JoinpointLevel.LIFECYCLE


# ---------------------------------------------------------------------------
# Weaving-operation buckets — kept inline for readability
# ---------------------------------------------------------------------------

_APPEND_MODES: frozenset[WeavingOperation | str] = frozenset(
    {
        WeavingOperation.INSERT,
        WeavingOperation.ANNOTATE,
        WeavingOperation.WARN,
        WeavingOperation.VERIFY,
        WeavingOperation.DEFER,
        "insert",
        "annotate",
        "warn",
        "verify",
        "defer",
    }
)

_OVERWRITE_MODES: frozenset[WeavingOperation | str] = frozenset(
    {
        WeavingOperation.REPLACE,
        WeavingOperation.REWRITE,
        WeavingOperation.COMPRESS,
        WeavingOperation.SUPPRESS,
        WeavingOperation.BLOCK,
        WeavingOperation.ESCALATE,
        "replace",
        "rewrite",
        "compress",
        "suppress",
        "block",
        "escalate",
    }
)


# ---------------------------------------------------------------------------
# Adapter
# ---------------------------------------------------------------------------


class CustomHostAdapter(HostAdapter):
    """Translate a custom host's events into JoinpointEvents (and back).

    Out of the box this handles the five most useful joinpoints
    (``runtime_start``, ``on_user_input``, ``before_response``,
    ``before_tool_call``, ``before_memory_write``) for the event-name
    conventions most frameworks use (``type`` / ``name`` /
    ``event`` / ``event_name``, first **mapped** value wins). Tune
    :data:`EVENT_TO_JOINPOINT` and :data:`_EVENT_NAME_KEYS` for anything
    more bespoke.
    """

    def __init__(
        self,
        host_name: str = "custom",
        *,
        event_map: dict[str, str] | None = None,
    ) -> None:
        self._host_name = host_name
        # Per-instance override of :data:`EVENT_TO_JOINPOINT` — handy
        # for tests and for multi-host topologies where each host
        # speaks a slightly different event vocabulary.
        self._event_map = dict(event_map) if event_map is not None else dict(EVENT_TO_JOINPOINT)

    @property
    def host_name(self) -> str:
        return self._host_name

    @property
    def event_map(self) -> dict[str, str]:
        """Live view of the host-event → joinpoint mapping (mutable)."""
        return self._event_map

    # ------------------------------------------------------------------
    # event → joinpoint
    # ------------------------------------------------------------------

    def map_host_event(self, event: dict) -> JoinpointEvent | None:
        """Translate one inbound host event into a :class:`JoinpointEvent`.

        Returns ``None`` when no :data:`_EVENT_NAME_KEYS` field yields a
        non-empty string that appears in :attr:`event_map` — the runtime
        treats that as "ignore", not as an error.

        Raises :class:`ValueError` when ``event`` is not a mapping —
        most frameworks emit dict-shaped events, but a list / scalar
        is always a bug at the call site.
        """
        if not isinstance(event, dict):
            raise ValueError(f"map_host_event expects a dict, got {type(event).__name__}")

        host_event_name = _first_mapped_host_event_name(event, self._event_map)
        if host_event_name is None:
            return None
        joinpoint_name = self._event_map[host_event_name]

        entry = JOINPOINT_CATALOG.get(joinpoint_name)
        level = entry.level if entry is not None else _FALLBACK_LEVEL

        return JoinpointEvent(
            id=str(event.get("id") or uuid.uuid4()),
            level=int(level),
            name=joinpoint_name,
            host=str(event.get("host") or self._host_name),
            agent_session_id=event.get("agent_session_id"),
            host_round_id=(
                event.get("host_round_id") or event.get("turn_id") or event.get("weave_id")
            ),
            ts=_coerce_ts(event.get("ts")),
            payload=_build_payload(event),
        )

    def map_host_events(self, events: Iterable[dict]) -> Iterable[JoinpointEvent]:
        """Streaming variant — yields successful mappings, drops :py:obj:`None`."""
        for event in events:
            jp = self.map_host_event(event)
            if jp is not None:
                yield jp

    # ------------------------------------------------------------------
    # injection → host context
    # ------------------------------------------------------------------

    def apply_injection(self, injection: ConcernInjection, host_context: dict) -> dict:
        """Return a new context with every row in ``injection`` folded in.

        Deep-copies ``host_context`` first so callers can diff
        before / after without accidental mutation. Each
        :class:`Injection` row's ``target`` is split on ``.`` and walked
        into a nested dict, creating missing intermediate dicts as
        needed; the ``mode`` then decides whether to append (``\\n``-
        separated) or overwrite the leaf.

        Rows with an empty ``target`` are silently dropped — there's
        no sensible place to write them.
        """
        out: dict[str, Any] = copy.deepcopy(host_context) if host_context else {}
        for row in injection.injections:
            _apply_row(out, row)
        return out


# ---------------------------------------------------------------------------
# Internals — kept module-level so they're easy to read and override
# ---------------------------------------------------------------------------


def _first_mapped_host_event_name(
    event: dict,
    event_map: dict[str, str],
) -> str | None:
    """First non-empty string among :data:`_EVENT_NAME_KEYS` that maps."""
    for key in _EVENT_NAME_KEYS:
        value = event.get(key)
        if isinstance(value, str) and value and value in event_map:
            return value
    return None


def _build_payload(event: dict) -> dict[str, Any]:
    """Return the joinpoint payload for ``event``.

    Honours an explicit ``payload`` field if present (a common
    convention); otherwise mirrors every non-envelope field from the
    event into ``payload`` so pointcut strategies can see the host's
    full event shape without losing data.
    """
    explicit = event.get("payload")
    if isinstance(explicit, dict):
        return dict(explicit)
    return {k: v for k, v in event.items() if k not in _ENVELOPE_KEYS}


def _coerce_ts(value: Any) -> datetime:
    if isinstance(value, datetime):
        return value if value.tzinfo else value.replace(tzinfo=UTC)
    if isinstance(value, str):
        try:
            parsed = datetime.fromisoformat(value)
        except ValueError:
            return datetime.now(tz=UTC)
        return parsed if parsed.tzinfo else parsed.replace(tzinfo=UTC)
    return datetime.now(tz=UTC)


def _apply_row(out: dict[str, Any], row: Injection) -> None:
    segments = [p for p in row.target.split(".") if p]
    if not segments:
        return
    *parents, leaf = segments
    node = out
    for seg in parents:
        nxt = node.get(seg)
        if not isinstance(nxt, dict):
            nxt = {}
            node[seg] = nxt
        node = nxt
    _write_leaf(node, leaf, row)


def _write_leaf(parent: dict[str, Any], leaf: str, row: Injection) -> None:
    if row.mode in _APPEND_MODES:
        cur = parent.get(leaf)
        if isinstance(cur, str) and cur:
            parent[leaf] = f"{cur}\n{row.content}"
        elif cur is None or cur == "":
            parent[leaf] = row.content
        else:
            # Non-string slot — replace rather than stringify so we
            # don't corrupt host-typed fields.
            parent[leaf] = row.content
    elif row.mode in _OVERWRITE_MODES:
        parent[leaf] = row.content
    else:
        # Unknown / future operation — safest default is append-like merge.
        cur = parent.get(leaf)
        if isinstance(cur, str) and cur:
            parent[leaf] = f"{cur}\n{row.content}"
        else:
            parent[leaf] = row.content


__all__ = ["EVENT_TO_JOINPOINT", "CustomHostAdapter"]
